/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package apresentacao;

import java.util.Timer;
import java.util.TimerTask;
import modelo.Controle;
import modelo.Estaticos;
import modelo.Serial;

/**
 *
 * @author Rever
 */
public class frmPrincipal extends javax.swing.JDialog {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        atualizarTela();
    }

    public void atualizarTela() {
        Timer timer = new Timer();
        timer.scheduleAtFixedRate(new TimerTask() {
            public void run() {

                lblUmidadeValor.setText(Estaticos.umidade);
                lblTemperaturaValor.setText(Estaticos.temperatura);
                lblPrecipitacaoValor.setText(Estaticos.precipitacao);

                if (Estaticos.coletaSerial) {
                    Controle controle = new Controle();
                    System.out.println(controle.mensagem);
                }
            }
        }, 10000, 10000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblTemperatura = new javax.swing.JLabel();
        lblTemperaturaValor = new javax.swing.JLabel();
        lblUmidade = new javax.swing.JLabel();
        lblUmidadeValor = new javax.swing.JLabel();
        lblPrecipitacao = new javax.swing.JLabel();
        lblPrecipitacaoValor = new javax.swing.JLabel();
        btnIniciarParar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estação Meteorológica");
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        lblTemperatura.setText("Temperatura");

        lblTemperaturaValor.setText("Valor");

        lblUmidade.setText("Umidade");

        lblUmidadeValor.setText("Valor");

        lblPrecipitacao.setText("Precipitação");

        lblPrecipitacaoValor.setText("Valor");

        btnIniciarParar.setText("Iniciar");
        btnIniciarParar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnIniciarPararActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTemperatura)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblUmidade)
                        .addComponent(lblPrecipitacao)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTemperaturaValor)
                    .addComponent(lblUmidadeValor)
                    .addComponent(lblPrecipitacaoValor))
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIniciarParar)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTemperatura)
                    .addComponent(lblTemperaturaValor))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUmidade)
                    .addComponent(lblUmidadeValor))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecipitacao)
                    .addComponent(lblPrecipitacaoValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnIniciarParar)
                .addGap(24, 24, 24))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarPararActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnIniciarPararActionPerformed
    {//GEN-HEADEREND:event_btnIniciarPararActionPerformed
        if (Estaticos.coletaSerial) {
            Estaticos.coletaSerial = false;
            btnIniciarParar.setText("Iniciar");
            System.out.println("Coleta Parada");
        } else {
            Estaticos.coletaSerial = true;
            Serial serial = new Serial();
            Thread s1 = new Thread(serial);
            s1.start();
            btnIniciarParar.setText("Parar");
            System.out.println("Coleta Iniciada");
        }
    }//GEN-LAST:event_btnIniciarPararActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        Estaticos.coletaSerial = false;
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmPrincipal dialog = new frmPrincipal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarParar;
    private javax.swing.JLabel lblPrecipitacao;
    private javax.swing.JLabel lblPrecipitacaoValor;
    private javax.swing.JLabel lblTemperatura;
    private javax.swing.JLabel lblTemperaturaValor;
    private javax.swing.JLabel lblUmidade;
    private javax.swing.JLabel lblUmidadeValor;
    // End of variables declaration//GEN-END:variables
}
